import type { Metadata } from "next";
import { Crimson_Pro, Nunito } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Providers from "@/lib/providers";
import Header from "@/components/Header";

const crimsonPro = Crimson_Pro({
  weight: ["400", "700"],
  variable: "--font-crimson-pro",
  subsets: ["latin"],
});

const nunito = Nunito({
  weight: ["400", "700"],
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Plate Haven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${crimsonPro.variable} ${nunito.variable} antialiased min-h-screen font-body`}
      >
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>
        <footer className="p-8 pb-2 bg-footer-background text-white">
          <div className="lg:container mx-auto">
            <ul className="mb-8 text-center flex flex-col lg:flex-row gap-4 lg:justify-between">
              <li>
                <Link href="/menu">Menu</Link>
              </li>
              <li>
                <Link href="/">About Us</Link>
              </li>
              <li>
                <Link href="/">Nutritional Info</Link>
              </li>
              <li>
                <Link href="/">Customer Support</Link>
              </li>
              <li>
                <Link href="/">Gift Cards</Link>
              </li>
              <li>
                <Link href="/">Careers</Link>
              </li>
              <li>
                <Link href="/">Community</Link>
              </li>
            </ul>
            <p className="text-center">
              © 2025 Plate Haven All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
